sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_1/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_2/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_3/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_4/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_5/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_6/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_7/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_8/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_9/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_10/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_11/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_12/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_13/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_14/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_15/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_16/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_17/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_18/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/7p6z_19/TM_submit_CPU.sbatch
