sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_1/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_2/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_3/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_4/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_5/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_6/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_7/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_8/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_9/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_10/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_11/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_12/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_13/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_14/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_15/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_16/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_17/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_18/submit_job.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates_pytme/ha_19/submit_job.sbatch
