sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_1/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_2/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_3/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_4/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_5/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_6/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_7/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_8/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_9/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_10/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_11/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_12/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_13/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_14/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_15/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_16/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_17/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_18/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/sphere_19/TM_submit_CPU.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_1/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_2/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_3/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_4/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_5/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_6/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_7/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_8/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_9/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_10/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_11/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_12/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_13/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_14/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_15/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_16/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_17/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_18/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emoji_19/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_1/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_2/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_3/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_4/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_5/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_6/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_7/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_8/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_9/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_10/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_11/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_12/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_13/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_14/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_15/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_16/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_17/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_18/TM_submit.sbatch
sbatch /Users/vmaurer/src/ribosomeSpheres/templates/emd3228_19/TM_submit.sbatch
